services:
  web:
    build: .
    container_name: todolist_backend
    command: gunicorn todolist.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16
    container_name: todolist_db
    restart: always
    environment:
      POSTGRES_DB: todolist_db
      POSTGRES_USER: todolist_user
      POSTGRES_PASSWORD: GHost45223374!@#
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: